spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #format_sql: true
        #use_sql_comments: true
    #show-sql: true
    open-in-view: false
    # defer-datasource-initialization: true

queue:
  scan-time: "0 * * * * *"
  expired-time: "1"

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
