spring:
  data:
    redis:
      host: redis
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# 개발 및 테스트 환경 H2 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #format_sql: true
        #use_sql_comments: true
    #show-sql: true
    open-in-view: false
    defer-datasource-initialization: true


# Mysql 설정 
#  jpa:
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:33060/mysql?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 1234

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true

queue:
  scan-time: "0 * * * * *"

seat:
  scan-time: "0 * * * * *"

logging:
  level:
    org:
      springframework:
        transaction: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health