insert into concert (concert_id, name, singer, created_at, updated_at) values(1, '다나카 내한 공연［SAYONARA... TANAKA]', '다나카', now(), now());
insert into concert (concert_id, name, singer, created_at, updated_at) values(2, '2024 성시경의 축가 콘서트', '성시경', now(), now());
insert into concert (concert_id, name, singer, created_at, updated_at) values(3, '황영웅 대전콘서트 〈봄날의 고백>', '황영웅', now(), now());
insert into concert (concert_id, name, singer, created_at, updated_at) values(4, '김태우 2024 T-PARTY < ROOM 512 >', '김태우', now(), now());

insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (1, 1, '세종예술의전당', '2024-04-10T00:00:00', '2024-10-15T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (2, 1, '건국대학교 새천년관 대공연장', '2024-04-11T00:00:00', '2024-10-16T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (3, 1, '컨벤션센터 2전시장', '2024-04-08T00:00:00', '2024-10-10T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (4, 2, '광주예술의전당 대극장', '2024-04-11T00:00:00', '2024-10-15T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (5, 2, '고양아람누리 아람극장', '2024-04-11T00:00:00', '2024-10-18T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (6, 3, '경남문화예술회관 대공연장', '2024-04-11T00:00:00', '2024-10-23T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (7, 3, '경기아트센터 대극장', '2024-04-11T00:00:00', '2024-10-14T00:00:00', now(), now());
insert into concert_option (concert_option_id, concert_id, venue, reservation_start_date, start_date, created_at, updated_at) values (8, 4, '경북대학교 대강당', '2024-04-13T00:00:00', '2024-10-12T00:00:00', now(), now());

INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 1, now(), DATEADD(MINUTE, -2, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 2, now(), DATEADD(MINUTE, -1, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 3, now(), DATEADD(MINUTE, 1, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 4, now(), DATEADD(MINUTE, 2, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 5, now(), DATEADD(MINUTE, 3, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 6, now(), DATEADD(MINUTE, 4, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 7, now(), DATEADD(MINUTE, 5, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 8, now(), DATEADD(MINUTE, 6, NOW()));
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'TEMPORARY', 1000, 9, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 10, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 11, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 12, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 13, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 14, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'AVAILABLE', 1000, 15, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 16, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 17, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 18, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 19, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 20, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 21, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 22, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 23, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 24, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 25, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 26, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 27, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 28, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 29, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 30, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 31, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 32, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 33, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 34, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 35, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 36, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 37, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 38, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 39, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 40, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 41, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 42, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 43, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 44, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 45, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 46, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 47, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 48, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 49, now(), now());
INSERT INTO concert_seat (concert_option_id, status, price, seat_no, created_at, updated_at) VALUES (1, 'REVERSED', 1000, 50, now(), now());
